### ISSUE TITLE
slate and slatepack

### ISSUE THREAD

**Issue by jackzhp** [mimblewimble/grin-rfcs#88]
why should we be so complicated?

with grin, to send some grins from the sender to the receiver, the sender needs an output specified by the receiver(feature 1 byte, a commitment 33 byte, a proof 8+675 bytes). Once the sender has that 717 bytes, a tx is constructed, the tx can and should be sent to the receiver. either the sender or the receiver could post the tx to the network. 

And to receive, the payee prepares the above mentioned output(717 bytes) to the payer, the payer constructs the tx. the tx is then send to the payee. either of them can post the tx to the network.

why should it be that complicated? I feel that i don't understand slate and slatepack. 
Can someone shed some light on what I missed? Thanks in advance.

Jack.

**Comment by phyro** [comment]
Hi @jackzhp. Let's separate transaction building from sending it to the network. In order to send the transaction to the network, it needs to be first constructed. This includes having the kernel commitment signed by both parties. A signature can be put on the kernel only after both parties have provided their partial excess. Consider Alice sending money to Bob. The steps are:

1. Alice sends her partial excess `a_e*G` to Bob along with information that Bob can be paid 5 Grin
2. Bob creates an output holding 5 Grin together with a rangeproof and adds partial his excess `b_e*G` to the existing partial excess making it `(a_e + b_e)*G`. Bob now signs for this total excess (kernel commitment).
3. Alice receives the total excess and signs for `(a_e+b_e)*G` making a valid multisig on this kernel.

Once both parties have signed the kernel (step 3. above), the transaction can be broadcasted to the network. These are the 3 essential steps that have to be done in order to produce a _safe_ transaction. Alice can only broadcast the transaction after it has been returned from Bob and she attached her signature to it. We don't know of a way to reduce the number of steps without either switching to a different cryptographic scheme or making a transaction vulnerable to at least some attacks.

Considering this isn't really an issue with an RFC, I'll close this, but let this not discourage you from asking more questions if you're interested. You can continue here, on the forum or on keybase.

P.S. I have omitted kernel offset to simplify things.

**Comment by jackzhp** [comment]
thank you for replying to me. 

Yeah, you remind that the signature is an aggregation from 2 signatures.
